# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 19:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator]),
        ),
    ]
