# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160913_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(help_text='Content of the blog entry. May include HTML.'),
        ),
    ]
